---
# Before running roles inside this playbook, copy
# ``inventory/builders.sample`` as ``inventory/builders`` and edit it
# to provide info about your build instance(s)

# The base image can be built in a more automated fashio using Packer
# (see README but basically just adjust any variables in `image.json`
# and issue ths command: ``% packer build image.json``)
# or via the following command (in which case make sure you provided
# instance access details in ``inventory/builders`` for
# ``image-builder`` host group and uncommented ``image-builder``
# below):
#
#   % ansible-playbook -i inventory/builders image.yml
#     --extra-vars vnc_password=$CM_VNC_PWD
#     --extra-vars psql_galaxyftp_password=$CM_GALAXY_FTP_PWD
#     [--extra-vars cleanup=yes]
#
# - hosts: image-builder
- hosts: localhost
  connection: local
  sudo: yes
  roles:
    - role: galaxyprojectdotorg.cloudman-image
      # vnc_password: <a_password>  # Or specify via the command
      # psql_galaxyftp_password: <a_different_password>  # Or specify via the command

# ansible-playbook -i inventory/builders image.yml --extra-vars vnc_password=$CM_VNC_PWD --extra-vars psql_galaxyftp_password=$CM_GALAXY_FTP_PWD --extra-vars cleanup=no
