---

- name: Copy tool management scripts
  copy: src=scripts/{{ item }} dest={{ galaxy_server_dir }}/{{ item }} owner={{ galaxy_user_name }}
  with_items:
    - manage_bootstrap_user.py
    - install_tool_shed_tools.py

- name: Copy tool list file
  copy: src={{ shed_tool_list_file }} dest={{ galaxy_server_dir }}/shed_tool_list.yaml owner={{ galaxy_user_name }}

- name: Create Galaxy bootstrap user
  command: chdir={{ galaxy_server_dir }} {{ galaxy_venv_dir }}/bin/python manage_bootstrap_user.py -c {{ galaxy_config_file }} create -e {{ galaxy_admin_user }} -p {{ galaxy_admin_user_password }}
  register: api_key

- name: Set bootstrap user as Galaxy Admin
  lineinfile: dest={{ galaxy_config_file }} state=present insertafter="app:main" regexp="admin_users =" line="admin_users = {{ galaxy_admin_user }}"  #"

- include: restart_galaxy.yml

- name: Install Tool Shed tools as the bootstrap user
  command: chdir={{ galaxy_server_dir }} {{ galaxy_venv_dir }}/bin/python install_tool_shed_tools.py -t shed_tool_list.yaml -a {{ api_key.stdout_lines[0] }} -g http://127.0.0.1:8080/
  ignore_errors: true

- name: Remove tool management scripts/file
  file: dest={{ galaxy_server_dir }}/{{ item }} state=absent
  with_items:
    - manage_bootstrap_user.py
    - install_tool_shed_tools.py
    - shed_tool_list.yaml
